// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')

describe('Login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1201, height: 676 })
    await driver.findElement(By.id("basic-navbar-nav")).click()
    await driver.findElement(By.css(".btn-outline-success")).click()
    expect(await driver.findElement(By.css("#basic-navbar-nav > div:nth-child(2)")).getText()).toBe("Hola admin")
    await driver.findElement(By.css(".btn-outline-success")).click()
    {
      const value = await driver.findElement(By.css(".btn-outline-success")).getAttribute("value")
      expect(value).toBe("login")
    }
  })
})
