get http://127.0.0.1:4200/demos/formulario

###

put http://127.0.0.1:4200/demos/

###

get http://127.0.0.1:4200/demos/kkkk/127.0.0.14200

###

get http://localhost:4200/demos/cotilla/1?rows=20&page=0
Content-Type: application/json
Referer: http://mi.casa

{ "user": "admin", "password": "P@$$w0rd"}

###

get http://localhost:4200/demos/cotilla/1?rows=20
Content-Type: application/x-www-form-urlencoded

user=admin&password=P@$$w0rd¬intentos=100

###

get http://localhost:4200/demos/eco
Accept: application/octet-stream

###

get http://localhost:4200/api/actores?page=all&rows=10&order=first_name,last_name&proyection=first_name,last_name
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJlbXBAa2sua2siLCJuYW1lIjoiRW1wbGVhZG8iLCJyb2xlcyI6WyJVc3VhcmlvcyIsIkVtcGxlYWRvcyJdLCJpYXQiOjE2NTQzMzg4MDksImV4cCI6MTY1NDM0MjQwOX0.d_biTZ9AOvkQWb2aCaL5P7NISE2E-PeqH1lykz-qMLI

###

get http://localhost:4200/api/actores?page=all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJhZG1pbiIsIm5hbWUiOiJBZG1pbmlzdHJhZG9yIiwicm9sZXMiOlsiVXN1YXJpb3MiLCJBZG1pbmlzdHJhZG9yZXMiXSwiaWF0IjoxNjU0NTAyMTQ0LCJleHAiOjE2NTQ1MDU3NDR9.SIF3DJaML9vIStLpFypXCYbxB37VcJveYa21QN8URNc

###

get http://localhost:4200/api/actores?find=pe
###

get http://localhost:4200/api/actores/209

###

post http://localhost:4200/api/actores
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJhZG1pbiIsIm5hbWUiOiJBZG1pbmlzdHJhZG9yIiwicm9sZXMiOlsiVXN1YXJpb3MiLCJBZG1pbmlzdHJhZG9yZXMiXSwiaWF0IjoxNjU0NTIzOTUwLCJleHAiOjE2NTQ1Mjc1NTB9.PJ1SrZG7KUADzR-j7R0Xyyg5GoN0DE7N9-J9TiXj0o4
X-XSRF-TOKEN: 123456790ABCDEF
Content-Type: application/json

{
  "actor_id": 2,
  "first_name": "GRILLO",
  "last_name": "Grillo",
  "last_update": "2006-02-15T04:34:33.000Z"
}

###

put http://localhost:4200/api/actores/207
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJhZG1pbiIsIm5hbWUiOiJBZG1pbmlzdHJhZG9yIiwicm9sZXMiOlsiVXN1YXJpb3MiLCJBZG1pbmlzdHJhZG9yZXMiXSwiaWF0IjoxNjU0NTIzOTUwLCJleHAiOjE2NTQ1Mjc1NTB9.PJ1SrZG7KUADzR-j7R0Xyyg5GoN0DE7N9-J9TiXj0o4
X-XSRF-TOKEN: 123456790ABCDEF
Content-Type: application/json

{
  "actor_id": 207,
  "first_name": "PEPITO",
  "last_name": "Grillo",
  "last_update": "2006-02-15T04:34:33.000Z"
}

###

delete http://localhost:4200/api/actores/217

###

get http://localhost:4200/api/actores/1/peliculas

###

get http://localhost:4200/api/ciudades/1?mode=details

###

post http://localhost:4200/api/login
Content-Type: application/json

{ "name": "admin", "password": "P@$$w0rd" }

###

post http://localhost:4200/api/login?cookie=true
Content-Type: application/json

{ "name": "emp@kk.kk", "password": "P@$$w0rd" }

###

get http://localhost:4200/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJhZG1pbiIsIm5hbWUiOiJBZG1pbmlzdHJhZG9yIiwicm9sZXMiOlsiVXN1YXJpb3MiLCJBZG1pbmlzdHJhZG9yZXMiXSwiaWF0IjoxNjU0NDk3NjY2LCJleHAiOjE2NTQ1MDEyNjZ9.thQ-Li-V7C4Dhqkdo4qL_C2a1pmVtz5Zy5Wg0zdOG4o

###

post  http://localhost:4200/api/auth
Set-Cookie: XSRF-TOKEN=123456790ABCDEF; Path=/,Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJlbXBAa2sua2siLCJuYW1lIjoiRW1wbGVhZG8iLCJyb2xlcyI6WyJVc3VhcmlvcyIsIkVtcGxlYWRvcyJdLCJpYXQiOjE2NTQzMjM5MzksImV4cCI6MTY1NDMyNzUzOX0.I_AfrlIIPC8-vkIuih1Y5rjYoy5TydvJqEObas1rSXc; Path=/; 
x-xsrf-token: 123456790ABCDEF

###

post http://localhost:4200/api/register
Content-Type: application/json

{
  "username": "kk@kk.kk",
  "nombre": "kk",
  "password": "Pássw0rd",
  "roles": "Usuarios,Empleados"
}
###

post http://localhost:4200/api/login
Content-Type: application/json

{ "name": "kk@kk.kk", "password": "Pássw0rd" }

###

get http://localhost:4200/api/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJra0Bray5rayIsIm5hbWUiOiJrayIsInJvbGVzIjpbIlVzdWFyaW9zIl0sImlhdCI6MTY1NDY3ODg3MywiZXhwIjoxNjU0NjgyNDczfQ.8buvScPXH5hb1aCc-caPmifwZO030_-PRFQXvcA7mv8

###

put http://localhost:4200/api/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJra0Bray5rayIsIm5hbWUiOiJrayIsInJvbGVzIjpbIlVzdWFyaW9zIl0sImlhdCI6MTY1NDY3ODg3MywiZXhwIjoxNjU0NjgyNDczfQ.8buvScPXH5hb1aCc-caPmifwZO030_-PRFQXvcA7mv8
Content-Type: application/json

{
  "username": "kkk@kk.kk",
  "nombre": "kkk",
  "password": "Pássw0rd",
  "roles": "Usuarios,Empleados"
}

###

put http://localhost:4200/api/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJra0Bray5rayIsIm5hbWUiOiJrayIsInJvbGVzIjpbIlVzdWFyaW9zIl0sImlhdCI6MTY1NDY3ODg3MywiZXhwIjoxNjU0NjgyNDczfQ.8buvScPXH5hb1aCc-caPmifwZO030_-PRFQXvcA7mv8
Content-Type: application/json

{
  "oldpassword": "P@ssw0rd",
  "newpassword": "Pássw0rd"
}

###

get http://localhost:4200/admin/users


###

get http://localhost:4200/admin/users/kk@kk.kk
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJhZG1pbiIsIm5hbWUiOiJBZG1pbmlzdHJhZG9yIiwicm9sZXMiOlsiVXN1YXJpb3MiLCJBZG1pbmlzdHJhZG9yZXMiXSwiaWF0IjoxNjU1ODg0MjQ2LCJleHAiOjE2NTU4ODc4NDZ9.jNGE_jfdQhmT8MPhZpFspeQxy16KrZvPAx1aXUi3VMI

###

put http://localhost:4200/admin/users/kk@kk.kk
Content-Type: application/json

{
  "idUsuario": "kk@kk.kk",
  "nombre": "k",
  "roles": ["Usuarios","Administradores"]
}


###

put http://localhost:4200/admin/users/kk@kk.kk
Content-Type: application/json

{
  "idUsuario": "kk@kk.kk",
  "nombre": "kkk",
   "roles": ["Empleados"]
}

###

delete http://localhost:4200/admin/users/kk@kk.kk

###

get http://localhost:8001/auto/actors
Accept: application/xml

###

http://localhost:8010/actores
Accept: application/xml

