get http://127.0.0.1:4200/demos/formulario

###

put http://127.0.0.1:4200/demos/

###

get http://127.0.0.1:4200/demos/kkkk/127.0.0.14200

###

get http://localhost:4200/demos/cotilla/1?rows=20&page=0
Content-Type: application/json
Referer: http://mi.casa

{ "user": "admin", "password": "P@$$w0rd"}

###

get http://localhost:4200/demos/cotilla/1?rows=20
Content-Type: application/x-www-form-urlencoded

user=admin&password=P@$$w0rd¬intentos=100

###

get http://localhost:4200/demos/eco
Accept: application/octet-stream

###

get http://localhost:4200/api/actores?page=all&rows=10&order=first_name,last_name&proyection=first_name,last_name

###

get http://localhost:4200/api/actores?find=pe
###

get http://localhost:4200/api/actores/209

###

post http://localhost:4200/api/actores
Content-Type: application/json

{
  "actor_id": 2,
  "first_name": "GRILLO",
  "last_name": "Grillo",
  "last_update": "2006-02-15T04:34:33.000Z"
}

###

put http://localhost:4200/api/actores/209
Content-Type: application/json

{
  "actor_id": 209,
  "first_name": "PEPITO",
  "last_name": "Grillo",
  "last_update": "2006-02-15T04:34:33.000Z"
}

###

delete http://localhost:4200/api/actores/1

###

get http://localhost:4200/api/actores/1/peliculas

###

get http://localhost:4200/api/ciudades/1?mode=details
